security:
    providers:
        internal:
            entity:
                class: App\Entity\User\User
                property: username

    encoders:
        App\Entity\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/document, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
